-- AlterTable
ALTER TABLE "PaymentWebhookEvent"
ADD COLUMN "payloadHash" TEXT,
ADD COLUMN "deliveryCount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
